version: '3'

networks:
  3lips:
  adsb-network:
    external: true

services:

  api:
    restart: always
    build:
      context: .
      dockerfile: ./api/Dockerfile
    image: 3lips-api
    network_mode: host
    volumes:
      - ./config:/app/config
      - ./common:/app/common
    container_name: 3lips-api
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  event:
    restart: always
    build:
      context: ./event
      dockerfile: Dockerfile
    image: 3lips-event
    network_mode: host
    volumes:
      - ./config:/app/config
      - ./common:/app/common
      - ./test:/app/test
      - ./save:/app/save
    container_name: 3lips-event
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  cesium-apache:
    restart: always
    build:
      context: ./cesium
      dockerfile: Dockerfile
    image: cesium-apache
    network_mode: host
    container_name: 3lips-cesium
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
